In [21]:
import numpy as np 
import pandas as pd

In [22]:
df = pd.read_csv('movies_dataset.csv')
df.head()

,id,title,overview,genre
0,1560520,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...","['Animation', 'Action', 'Adventure', 'Drama']"
1,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...","['Animation', 'Adventure', 'Fantasy', 'Action']"
2,1007757,Swapped,"A small woodland creature and a majestic bird,...","['Adventure', 'Animation', 'Family', 'Fantasy']"
3,1632181,Accidental Partners,Two women discover they were both scammed by t...,"['Comedy', 'Romance']"
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,"['Animation', 'Action', 'Fantasy']"

Text preprocessing on the overview

In [23]:
df['overview'][0].lower()

'arkham asylum has been destroyed, and all its inmates have been unleashed upon gotham city. as batman races to round up some of his greatest enemies, he is pushed to his physical and mental limits and into a final confrontation with a new threat: the man called bane!'

In [24]:
df['overview'] = df['overview'].str.lower()

In [25]:
df.head()

,id,title,overview,genre
0,1560520,Batman: Knightfall Part 1: Knightfall,"arkham asylum has been destroyed, and all its ...","['Animation', 'Action', 'Adventure', 'Drama']"
1,980431,Avatar Aang: The Last Airbender,"avatar aang, the world's last airbender, learn...","['Animation', 'Adventure', 'Fantasy', 'Action']"
2,1007757,Swapped,"a small woodland creature and a majestic bird,...","['Adventure', 'Animation', 'Family', 'Fantasy']"
3,1632181,Accidental Partners,two women discover they were both scammed by t...,"['Comedy', 'Romance']"
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,the demon slayer corps are drawn into the infi...,"['Animation', 'Action', 'Fantasy']"

In [26]:
df['overview'][3]

'two women discover they were both scammed by the same man (who also got them pregnant). they form an alliance to take revenge.'

Removing html if present

In [27]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',str(text))

df['overview'] = df['overview'].apply(remove_html_tags)

Removing url if present

In [28]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', str(text))

df['overview'] = df['overview'].apply(remove_url)

Removing punctuation

In [29]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [30]:
exclude = string.punctuation

In [31]:
df['overview'][1]

"avatar aang, the world's last airbender, learns of an ancient power that could save his culture from extinction. with the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve."

In [32]:
def remove_punc_fast(text):
    return text.translate(str.maketrans('', '', exclude))

df['overview'] = df['overview'].apply(remove_punc_fast)

In [33]:
df['overview'][1]

'avatar aang the worlds last airbender learns of an ancient power that could save his culture from extinction with the help of his friends he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve'